version: '3'

services:
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-neo4j123456}
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_auth_enabled=true
    volumes:
      - neo4j_data:/data
    networks:
      - neo4j_elk_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ES_PASSWORD:-elastic123456}
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - neo4j_elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ES_USER:-elastic}
      - ELASTICSEARCH_PASSWORD=${ES_PASSWORD:-elastic123456}
    depends_on:
      - elasticsearch
    networks:
      - neo4j_elk_network

  logstash:
    build:
      context: .
      dockerfile: Dockerfile.logstash
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY:-localhost,127.0.0.1}
    ports:
      - "${LOGSTASH_BEATS_PORT:-5044}:5044"  # Beats
      - "${LOGSTASH_TCP_PORT:-1514}:1514"    # TCP
      - "${LOGSTASH_HTTP_PORT:-8080}:8080"   # HTTP
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ES_USER:-elastic}
      - ELASTICSEARCH_PASSWORD=${ES_PASSWORD:-elastic123456}
      - LOGSTASH_TCP_PORT=${LOGSTASH_TCP_PORT:-1514}
      - LOGSTASH_HTTP_PORT=${LOGSTASH_HTTP_PORT:-8080}
      - LOGSTASH_BEATS_PORT=${LOGSTASH_BEATS_PORT:-5044}
      - RUBYGEMS_MIRROR=${RUBYGEMS_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn/rubygems/}
    volumes:
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
      - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - logstash_data:/usr/share/logstash/data
    depends_on:
      - elasticsearch
    networks:
      - neo4j_elk_network

networks:
  neo4j_elk_network:
    driver: bridge

volumes:
  neo4j_data:
  elasticsearch_data:
  logstash_data: 