cluster.name: "neo4j-elk-cluster"
network.host: 0.0.0.0
http.port: 9200

# 单节点配置
discovery.type: single-node

# 内存配置
bootstrap.memory_lock: true
bootstrap.system_call_filter: false

# 安全配置
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true

# 跨域配置
http.cors.enabled: true
http.cors.allow-origin: "*"

# 索引配置
action.destructive_requires_name: true 